# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-12 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='t_Request',
        ),
    ]
