# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotline', '0002_auto_20181112_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_request',
            name='question',
            field=models.TextField(blank=True, max_length=550, verbose_name='Вопрос'),
        ),
    ]
