# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-12 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotline', '0003_auto_20181112_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_request',
            name='age',
            field=models.CharField(choices=[('взрослые', 'дети'), ('дети', 'взрослые')], default='дети', max_length=10, verbose_name='Вопрос по'),
        ),
    ]
